#!/usr/bin/env python3
"""Convert assets/logos/*.png into compact GFX monochrome bitmaps."""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path


WIDTH = 16
HEIGHT = 16
THRESHOLD = "90%"
PROJECT_ROOT = Path(__file__).resolve().parents[1]
INPUT_DIR = PROJECT_ROOT / "assets" / "logos"
OUTPUT_FILE = PROJECT_ROOT / "src" / "airline_logos.generated.cpp"


def symbol_for(stem: str) -> str:
    if stem == "default":
        return "kLogoDefault"
    return "kLogo" + stem


def convert_logo(magick: str, path: Path) -> list[int]:
    command = [
        magick,
        str(path),
        "-background",
        "white",
        "-alpha",
        "remove",
        "-alpha",
        "off",
        "-thumbnail",
        f"{WIDTH}x{HEIGHT}",
        "-gravity",
        "center",
        "-extent",
        f"{WIDTH}x{HEIGHT}",
        "-colorspace",
        "Gray",
        "-threshold",
        THRESHOLD,
        "-depth",
        "8",
        "gray:-",
    ]
    pixels = subprocess.run(command, check=True, capture_output=True).stdout
    if len(pixels) != WIDTH * HEIGHT:
        raise RuntimeError(
            f"{path.name}: expected {WIDTH * HEIGHT} pixels, got {len(pixels)}"
        )

    packed: list[int] = []
    for y in range(HEIGHT):
        for byte_x in range((WIDTH + 7) // 8):
            value = 0
            for bit in range(8):
                x = byte_x * 8 + bit
                if x < WIDTH and pixels[y * WIDTH + x] < 128:
                    value |= 0x80 >> bit
            packed.append(value)
    return packed


def format_array(symbol: str, data: list[int]) -> str:
    rows = []
    row_bytes = (WIDTH + 7) // 8
    for offset in range(0, len(data), row_bytes):
        row = ", ".join(f"0x{value:02X}" for value in data[offset : offset + row_bytes])
        rows.append(f"    {row},")
    return (
        f"const uint8_t {symbol}[] PROGMEM = {{\n"
        + "\n".join(rows)
        + "\n};\n"
    )


def main() -> None:
    magick = shutil.which("magick")
    if magick is None:
        raise SystemExit("ImageMagick 7 is required (the 'magick' command was not found)")

    paths = sorted(INPUT_DIR.glob("*.png"), key=lambda path: path.stem)
    codes: list[tuple[str, str]] = []
    default_path: Path | None = None
    arrays: list[str] = []

    for path in paths:
        if path.stem == "default":
            default_path = path
            continue
        code = path.stem.upper()
        if not re.fullmatch(r"[A-Z0-9]{3}", code):
            raise SystemExit(f"Invalid logo filename {path.name}; use a three-character ICAO code")
        symbol = symbol_for(code)
        arrays.append(format_array(symbol, convert_logo(magick, path)))
        codes.append((code, symbol))

    if default_path is None:
        raise SystemExit("assets/logos/default.png is required")
    arrays.append(
        format_array(symbol_for("default"), convert_logo(magick, default_path))
    )

    entries = "\n".join(
        f'    {{"{code}", {symbol}}},' for code, symbol in codes
    )
    output = f'''// Generated by tools/generate_airline_logos.py. Do not edit by hand.
#include "airline_logos.h"

#include <Arduino.h>

#include <cctype>
#include <cstring>

namespace skyprint {{
namespace {{

{chr(10).join(arrays)}
struct LogoEntry {{
  char code[4];
  const uint8_t* bitmap;
}};

const LogoEntry kLogoEntries[] = {{
{entries}
}};

}}  // namespace

const uint8_t* airlineLogoForCallsign(const std::string& callsign) {{
  if (callsign.size() >= 3) {{
    char code[4] = {{}};
    for (size_t index = 0; index < 3; ++index) {{
      const unsigned char character =
          static_cast<unsigned char>(callsign[index]);
      if (!std::isalpha(character)) return kLogoDefault;
      code[index] = static_cast<char>(std::toupper(character));
    }}
    for (const LogoEntry& entry : kLogoEntries) {{
      if (std::memcmp(code, entry.code, 3) == 0) return entry.bitmap;
    }}
  }}
  return kLogoDefault;
}}

}}  // namespace skyprint
'''
    OUTPUT_FILE.write_text(output, encoding="utf-8")
    print(f"Generated {OUTPUT_FILE.relative_to(PROJECT_ROOT)} from {len(codes) + 1} logos")


if __name__ == "__main__":
    main()
